// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUr3GKh856pgwNe1nV3B79nYvL5-Igugg',
    appId: '1:354608667901:web:356b85feb3acd03975b294',
    messagingSenderId: '354608667901',
    projectId: 'bookswap-9c679',
    authDomain: 'bookswap-9c679.firebaseapp.com',
    storageBucket: 'bookswap-9c679.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFZOu9L-NBhq-XpX-_JWAIZ7EOXdQxiQ',
    appId: '1:354608667901:android:63a61a2fb1477a9f75b294',
    messagingSenderId: '354608667901',
    projectId: 'bookswap-9c679',
    storageBucket: 'bookswap-9c679.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPXD2d7Aiw8SwlXanf1_6nhlQ-Pb85DrQ',
    appId: '1:354608667901:ios:60eb5e9fca75194475b294',
    messagingSenderId: '354608667901',
    projectId: 'bookswap-9c679',
    storageBucket: 'bookswap-9c679.firebasestorage.app',
    iosBundleId: 'com.example.swap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUr3GKh856pgwNe1nV3B79nYvL5-Igugg',
    appId: '1:354608667901:web:8f76025c63a7e14975b294',
    messagingSenderId: '354608667901',
    projectId: 'bookswap-9c679',
    authDomain: 'bookswap-9c679.firebaseapp.com',
    storageBucket: 'bookswap-9c679.firebasestorage.app',
  );
}
